:up: update node16 -> 20
medyagh/setup-minikube pull request #383
Opened 2024-02-10 05:21 UTC by nilwurtz

Hi,

I've confirmed that npm run all passes successfully, which looks good to me. Additionally, I've noticed that @types/node is already updated to the 20.x series.

This PR is related to issue #382.

2024-02-13 20:03 UTC, wayne-manselle-apex commented
@medyagh - you the right person to tag for a workflow approval and review?

2024-02-15 14:28 UTC, spowelljr commented
Hi @nilwurtz, thanks for the PR!

One request, would you mind adding the following to `.github/workflows/test.yml` line 15:
```
- uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
  with:
    node-version: 20
```

That way we'll be testing with the same version, the GitHub Action Runner has Node 18 installed by default.

2024-02-15 16:32 UTC, nilwurtz commented
@spowelljr Thank you for pointing that out. I hadn't noticed it. I have now pushed.

2024-02-15 18:05 UTC, spowelljr requested changes

2024-02-15 18:05 UTC, spowelljr commented on .github/workflows/test.yml
> +        with:
```suggestion
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
```
Just need to define the `setup-node` action as well

2024-02-16 16:13 UTC, spowelljr approved these changes
Thanks for the PR!

2024-02-16 16:13 UTC, merged